<?php
namespace App\Extensions\Catalog\Admin;

use Simflex\Admin\Base;

class Stock extends Base
{
    protected function showCell($field, $row)
    {
        if ($field->name == 'total') {
            $row['total'] = $row['available'] + $row['in_orders'];
        }

        if ($field->name == 'available' && $row['available'] < 1) {
            if (!$row['available']) {
                $row['available'] = '<strong>0</strong>';
            } else {
                $row['available'] = '<span style="color: #ef2828">' . $row['available'] . '</span>';
            }
        }

        parent::showCell($field, $row); // TODO: Change the autogenerated stub
    }
}